name: IERS Auth Service Deployment

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: iers-auth-service
  IMAGE_TAG: latest
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
            sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            
            cd /home/ubuntu/iers-project
            sudo docker compose up -d --no-deps auth-service
            
            
            
            
            
            
            
            
            
            

services:
  # 1._____ EUREKA SERVER _________
  eureka-server:
    image: 465891279952.dkr.ecr.ap-south-1.amazonaws.com/iers-fyp:latest
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"

  # 2.__________API GATEWAY__________
  api-gateway:
    image: 465891279952.dkr.ecr.ap-south-1.amazonaws.com/iers-api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8165:8165"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # 3. __________POSTGRES DATABASE__________
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: IERS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rana462
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d IERS" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # 4. ________AUTHENTICATION SERVICE_____________
  auth-service:
    image: 465891279952.dkr.ecr.ap-south-1.amazonaws.com/iers-auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/IERS
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rana462
      EMAIL_USERNAME: sp23-bse-021@cuilahore.edu.pk
      EMAIL_PASSKEY: ptvoxqfxwjxkqyqv
      GOOGLE_CLIENT_ID: vk2mnrk5j5dmi0u12evaemuf0an285ek.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
volumes:
  pgdata: