script: |
  docker pull ranaasad462/iers-fyp:latest
  docker rm -f iers-authentication || true
  
  docker run -d \
    --name iers-authentication \
    -p 8080:8080 \
    -e SPRING_DATASOURCE_URL=jdbc:postgresql://172.31.34.111:5432/IERS \
    -e POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} \
    -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
    -e EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} \
    -e EMAIL_PASSKEY=${{ secrets.EMAIL_PASSKEY }} \
    -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
    -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
    ranaasad462/iers-fyp:latest